routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\SingerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [SingerController::class, 'index'])->name('index');

Route::get('/find', function () {
    return view('guest.find');
})->name('find');

Route::get('/find/result', [SingerController::class, 'show'])->name('show');

Route::middleware('auth')->group(function () {

    Route::resource('admin/singers', 'App\Http\Controllers\AdminController',
        ['parameters' =>[
            'singers' => 'id']]
    );

});

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/add.blade.php
@extends('admin.schema')

@section('content')
    <div class="container">
        <form action="{{route('singers.store')}}" method="post">
            @csrf
            <div class="row g-3">
                <div class="col-sm-6">
                    <label for="firstName" class="form-label">Singer name</label>
                    <input type="text" class="form-control" id="firstName" placeholder="" value="" required="" name="singer">
                    <div class="invalid-feedback">
                        Valid singer name is required.
                    </div>
                </div>

                <div class="col-sm-6">
                    <label for="songName" class="form-label">Song name</label>
                    <input type="text" class="form-control" id="songName" placeholder="" value="" required="" name="song">
                    <div class="invalid-feedback">
                        Valid Song name is required.
                    </div>
                </div>
                <div class="col-sm-6">
                    <label for="Balu" class="form-label">Balu</label>
                    <input type="text" class="form-control" id="Balu" placeholder="" value="" required="" name="balu">
                    <div class="invalid-feedback">
                        Valid Balu is required.
                    </div>
                </div>

                <div class="col-md-5">
                    <label for="country" class="form-label">Country</label>
                    <select class="form-select" id="country" required="" name="country">
                        @foreach($countries as $country)
                        <option value='{{ $country->id }}'>{{$country->name}}</option>
                        @endforeach
                    </select>
                    <div class="invalid-feedback">
                        Please select a valid country.
                    </div>
                </div>

            </div>
            <button class="w-100 btn btn-primary btn-lg" type="submit">ADD</button>
        </form>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.schema')
@foreach($find as $el)
    @section('title','Edit '.$el->name)
@section('content')

    <div class="container">
        <form action="{{route('singers.update',['id' => $el->singr_id])}}" method="post">
            <input name="_method" type="hidden" value="PUT">
            @csrf
            <div class="row g-3">
                <div class="col-sm-6">
                    <label for="firstName" class="form-label">Singer name</label>
                    <input type="text" class="form-control" id="firstName" placeholder="" value="{{$el->singr_name}}"
                           required=""
                           name="singer">
                    <div class="invalid-feedback">
                        Valid singer name is required.
                    </div>
                </div>

                <div class="col-sm-6">
                    <label for="songName" class="form-label">Song name</label>
                    <input type="text" class="form-control" id="songName" placeholder="" value="{{$el->song_name}}"
                           required=""
                           name="song">
                    <div class="invalid-feedback">
                        Valid Song name is required.
                    </div>
                </div>
                <div class="col-sm-6">
                    <label for="Balu" class="form-label">Balu</label>
                    <input type="text" class="form-control" id="Balu" placeholder="" value="{{$el->rate}}" required=""
                           name="balu">
                    <div class="invalid-feedback">
                        Valid Balu is required.
                    </div>
                </div>

                <div class="col-md-5">
                    <label for="country" class="form-label">Country</label>
                    <select class="form-select" id="country" required="" name="country">
                        @foreach($countries as $country)
                            <option value='{{ $country->id }}'>{{$country->name}}</option>
                        @endforeach
                    </select>
                    <div class="invalid-feedback">
                        Please select a valid country.
                    </div>
                </div>

            </div>
            <button class="w-100 btn btn-primary btn-lg" type="submit">EDIT</button>
        </form>
    </div>

@endsection
@endforeach

resources/views/admin/index.blade.php
@extends('admin.schema')

@section('title','Admin home')

resources/views/admin/schema.blade.php
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
</head>
<body>
<center><h2>EuroVision Admin</h2></center>
<center>
    <a href="{{route('singers.create')}}">Add</a>
    <a href="{{ route('logout') }}"
       onclick="event.preventDefault();document.getElementById('logout-form').submit();">
        {{ __('Вийти') }}
    </a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
    </form>
</center>
@yield('content')
@if(isset($result))
    @foreach($result as $row)
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 fw-normal">{{$row->name}}</h4>
                <h1 class="my-0 fw-normal">{{$row->rate}}</h1>
            </div>
            <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Бали: {{$row->rate}}</li>
                    <li>Ім'я співака: {{$row->singr_name}}</li>
                    <li>Пісня: {{$row->song_name}}</li>
                </ul>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                    <form action="{{ route('singers.destroy' , ['id'=> $row->singr_id])}}" method="POST">
                        <input name="_method" type="hidden" value="DELETE">
                        {{ csrf_field() }}
                        <button  class="btn btn-danger" type="submit">Delete</button>
                    </form>
                    <a class="btn btn-success" href="{{route('singers.edit', ['id' => $row->singr_id])}}">Edit</a>
                </div>

            </div>
        </div>
    @endforeach
@endif
</body>
</html>